server:
  port: 8085
#application.yaml en eclipse
spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:http://localhost:8085
  cloud:
    config:
      enabled: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: secret
      
admin-paths:
  paths:
    -
      uri: "/usuarios/guardarUsuario/{1}[1-9]+[0-9]*"
      method: "POST"
    -
      uri: "/calificaciones/guardarCalificacion/{1}[1-9]+[0-9]*"